//! Minisign signing, in the shape Tauri's updater expects.
//!
//! Tauri stores signatures and keys as **base64 of the whole minisign file** —
//! comment lines included — rather than as the raw signature bytes. Anything
//! this tool writes into a manifest therefore has to go through the same
//! encoding, or the official updater will reject it.
//!
//! Signing is prehashed (minisign's `ED` algorithm: Ed25519 over a BLAKE2b
//! digest). That is what the `minisign` crate produces and what Tauri's own
//! signer produces, and `minisign-verify` — the crate Tauri verifies with —
//! accepts it.

use std::path::Path;

use base64::Engine as _;
use minisign::{PublicKeyBox, SecretKey, SecretKeyBox};

use tauri_updater_delta_core::release_identity::{
    parse_trusted_comment, ReleaseBinding, ReleaseIdentity,
};
use tauri_updater_delta_core::FileHash;

use crate::{Error, Result};

/// A minisign secret key, ready to sign release artifacts.
pub struct SigningKey {
    secret: SecretKey,
}

impl SigningKey {
    /// Load a key from the text form Tauri uses.
    ///
    /// Accepts either the raw minisign secret key file, or that file base64
    /// encoded, which is what `tauri signer generate` prints and what people
    /// paste into `TAURI_SIGNING_PRIVATE_KEY`. Trying raw first and base64
    /// second means both work without the caller having to say which it has.
    ///
    /// `password` of `None` means **the key is unencrypted** — not "ask the
    /// user". The `minisign` crate treats `None` as a request to prompt on the
    /// terminal, which in CI has no TTY: the run dies with
    /// `Device not configured (os error 6)`, or worse, hangs waiting for input
    /// that will never come. A release tool must never do either, so `None` is
    /// translated to an empty password here.
    pub fn from_str(text: &str, password: Option<String>) -> Result<Self> {
        let text = normalize_key_text(text, "secret key")?;

        let boxed = SecretKeyBox::from_string(&text)
            .map_err(|e| Error::Key(format!("unusable secret key: {e}")))?;

        // Always Some(_), never None — see the note on this function.
        let had_password = password.as_deref().is_some_and(|p| !p.is_empty());
        let secret = boxed
            .into_secret_key(Some(password.unwrap_or_default()))
            .map_err(|e| {
                // Tauri's CLI signs with rsign2, which runs its KDF even over an
                // empty password. The `minisign` crate skips encryption entirely
                // when the password is empty, so a key generated by
                // `tauri signer generate --password ""` cannot be opened here at
                // all — with any password. Say so, rather than leaving the user
                // staring at "wrong password" for a key that has none.
                if !had_password {
                    Error::Key(format!(
                        "could not unlock the secret key: {e}. If this key was made by \
                         `tauri signer generate` with an empty password, it cannot be read \
                         here: Tauri uses rsign2, which encrypts even with an empty \
                         password, while this tool uses the minisign crate, which does not. \
                         Regenerate the key with a real password and set \
                         TAURI_SIGNING_PRIVATE_KEY_PASSWORD."
                    ))
                } else {
                    Error::Key(format!("could not unlock the secret key: {e}"))
                }
            })?;

        Ok(Self { secret })
    }

    /// Load a key from a file on disk.
    pub fn from_file(path: &Path, password: Option<String>) -> Result<Self> {
        let text = std::fs::read_to_string(path)
            .map_err(|e| Error::Io(format!("reading key {}: {e}", path.display())))?;
        Self::from_str(&text, password)
    }

    /// Sign a file, returning the base64 form Tauri stores in its manifest.
    ///
    /// The signature is over the artifact's bytes, so it stays valid however the
    /// artifact reached the user — downloaded whole, or rebuilt from a patch.
    ///
    /// Produces a **legacy** signature: no authenticated release identity. Kept
    /// for the compatibility tests that pin what an older toolchain emits; the
    /// release path uses [`sign_release`].
    pub fn sign_file(&self, path: &Path) -> Result<String> {
        self.sign_with_comment(path, None)
    }

    /// Sign a released artifact, binding its identity into the signature.
    ///
    /// The identity is **derived here from the file being signed** — its BLAKE3
    /// and its length are read off the artifact, not accepted from the caller —
    /// so the signed statement cannot disagree with the bytes it covers. The
    /// caller supplies only what the file cannot know about itself: which
    /// application, version, platform and representation it is.
    ///
    /// This is one signature, not two. The identity rides in minisign's trusted
    /// comment, which the global signature already covers, so no second key and
    /// no second signing operation enter the release process.
    pub fn sign_release(&self, path: &Path, release: &ReleaseFacts<'_>) -> Result<String> {
        let identity = ReleaseIdentity {
            app_id: release.app_id.to_owned(),
            version: release.version.to_owned(),
            platform: release.platform.to_owned(),
            representation: release.representation.to_owned(),
            artifact_blake3: FileHash::of_file(path)?.to_hex(),
            artifact_size: std::fs::metadata(path)
                .map_err(|e| Error::Io(format!("stat {}: {e}", path.display())))?
                .len(),
            signed_at: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs())
                .unwrap_or(0),
        };

        let comment = identity.to_trusted_comment();
        // Refuse to sign something this build could not itself read back. A
        // release that emits an identity its own parser rejects would fail
        // closed on every client, and finding that out at release time is far
        // cheaper than finding it out from users.
        match parse_trusted_comment(&comment) {
            Ok(ReleaseBinding::Authenticated(parsed)) if *parsed == identity => {}
            other => {
                return Err(Error::Sign(format!(
                    "refusing to sign: the generated release identity does not round-trip \
                     through its own parser ({comment:?} -> {other:?})"
                )))
            }
        }

        self.sign_with_comment(path, Some(&comment))
    }

    fn sign_with_comment(&self, path: &Path, trusted_comment: Option<&str>) -> Result<String> {
        let file = std::fs::File::open(path)
            .map_err(|e| Error::Io(format!("opening {} to sign: {e}", path.display())))?;

        let signature = minisign::sign(None, &self.secret, file, trusted_comment, None)
            .map_err(|e| Error::Sign(format!("signing {}: {e}", path.display())))?;

        Ok(base64::engine::general_purpose::STANDARD.encode(signature.into_string()))
    }
}

/// What a released artifact cannot tell you about itself.
///
/// Everything else in the authenticated identity — digest, size — is read off
/// the file by [`SigningKey::sign_release`], so there is no way for the caller
/// to describe bytes other than the ones being signed.
#[derive(Debug, Clone)]
pub struct ReleaseFacts<'a> {
    /// Application bundle identifier, e.g. `dev.example.app`.
    pub app_id: &'a str,
    /// Release version, canonical semver.
    pub version: &'a str,
    /// Canonical `{os}-{arch}`.
    pub platform: &'a str,
    /// What the artifact is, e.g. `app-tar-gz-v1`.
    pub representation: &'a str,
}

/// Decode a Tauri-style base64 public key into its raw minisign form.
///
/// Useful for verifying what this tool produced without shelling out.
pub fn decode_public_key(text: &str) -> Result<minisign::PublicKey> {
    let text = normalize_key_text(text, "public key")?;
    PublicKeyBox::from_string(&text)
        .map_err(|e| Error::Key(format!("unusable public key: {e}")))?
        .into_public_key()
        .map_err(|e| Error::Key(format!("unusable public key: {e}")))
}

/// Minisign key and signature files all begin with this line.
const COMMENT_PREFIX: &str = "untrusted comment:";

/// Return the raw minisign file text, decoding the base64 wrapper if present.
///
/// This has to branch on *content*, not on whether parsing succeeds:
/// `SecretKeyBox::from_string` and `PublicKeyBox::from_string` accept any string
/// at all and only fail later, when the key is used. A "try raw, fall back to
/// base64" approach therefore never reaches the fallback, and a base64 key fails
/// much later with a confusing "Missing encoded key" instead.
fn normalize_key_text(text: &str, what: &str) -> Result<String> {
    let trimmed = text.trim();
    if trimmed.starts_with(COMMENT_PREFIX) {
        return Ok(trimmed.to_owned());
    }

    // Tauri stores keys base64-encoded; some tools wrap that at column 64.
    let compact: String = trimmed.chars().filter(|c| !c.is_whitespace()).collect();
    let decoded = base64::engine::general_purpose::STANDARD
        .decode(&compact)
        .map_err(|_| Error::Key(format!("{what} is neither minisign text nor base64")))?;
    let decoded = String::from_utf8(decoded)
        .map_err(|_| Error::Key(format!("{what} base64 did not decode to text")))?;

    if !decoded.trim_start().starts_with(COMMENT_PREFIX) {
        return Err(Error::Key(format!(
            "{what} base64 did not decode to a minisign file"
        )));
    }
    Ok(decoded.trim().to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;
    use minisign::KeyPair;

    /// An unencrypted keypair that can actually be serialised and read back.
    ///
    /// Not `generate_unencrypted_keypair()`: that leaves the secret key's
    /// checksum zeroed, and `write_checksum` is private to the minisign crate,
    /// so anything it produces fails to load again with "Wrong password for
    /// that key". Generating with an empty password writes the checksum and
    /// then skips encryption, which is the shape a real unencrypted key has.
    fn keypair() -> KeyPair {
        KeyPair::generate_encrypted_keypair(Some(String::new())).expect("generate keypair")
    }

    fn secret_key_text(pair: &KeyPair) -> String {
        pair.sk.to_box(None).expect("box secret key").into_string()
    }

    fn public_key_base64(pair: &KeyPair) -> String {
        pair.pk
            .to_box()
            .expect("box public key")
            .into_string()
            .lines()
            .nth(1)
            .expect("public key line")
            .to_owned()
    }

    /// Verify exactly the way Tauri's updater does: base64-decode the manifest
    /// field, parse it as a minisign signature, check it against the artifact
    /// bytes with `minisign-verify`.
    fn verify_like_tauri(signature_b64: &str, data: &[u8], pair: &KeyPair) -> bool {
        let Ok(decoded) = base64::engine::general_purpose::STANDARD.decode(signature_b64) else {
            return false;
        };
        let Ok(text) = String::from_utf8(decoded) else {
            return false;
        };
        let Ok(signature) = minisign_verify::Signature::decode(&text) else {
            return false;
        };
        let Ok(public) = minisign_verify::PublicKey::from_base64(&public_key_base64(pair)) else {
            return false;
        };
        public.verify(data, &signature, true).is_ok()
    }

    #[test]
    fn accepts_a_raw_minisign_key() {
        let pair = keypair();
        SigningKey::from_str(&secret_key_text(&pair), None).expect("raw minisign key should load");
    }

    #[test]
    fn accepts_the_base64_form_tauri_prints() {
        let pair = keypair();
        let encoded = base64::engine::general_purpose::STANDARD.encode(secret_key_text(&pair));
        SigningKey::from_str(&encoded, None).expect("base64 key should load");
    }

    #[test]
    fn accepts_a_password_protected_key() {
        let pair = KeyPair::generate_encrypted_keypair(Some("correct horse".to_owned()))
            .expect("generate keypair");
        let text = secret_key_text(&pair);

        SigningKey::from_str(&text, Some("correct horse".to_owned()))
            .expect("the right password should unlock the key");

        let Err(err) = SigningKey::from_str(&text, Some("wrong".to_owned())) else {
            panic!("the wrong password must not unlock the key");
        };
        assert!(matches!(err, Error::Key(_)));
    }

    #[test]
    fn a_key_that_will_not_open_without_a_password_explains_rsign2() {
        // The adoption-killer this guards against: someone follows Tauri's docs,
        // accepts the default of no password, and gets "Wrong password for that
        // key" about a key they never gave a password to. See DECISIONS #16.
        //
        // A true rsign2 interop test would need a key generated by Tauri's CLI,
        // which is a binary-only crate — and committing such a key is the hazard
        // class this project deliberately avoids. So what is pinned here is the
        // behaviour that actually prevents the silent failure: when unlocking
        // fails and no password was supplied, the error must name the cause and
        // the remedy rather than blaming a password that does not exist.
        let pair = KeyPair::generate_encrypted_keypair(Some("has-a-password".to_owned()))
            .expect("generate keypair");
        let Err(err) = SigningKey::from_str(&secret_key_text(&pair), None) else {
            panic!("a key needing a password must not open without one");
        };
        let message = err.to_string();
        for expected in [
            "rsign2",
            "empty password",
            "TAURI_SIGNING_PRIVATE_KEY_PASSWORD",
        ] {
            assert!(
                message.contains(expected),
                "the error must mention {expected:?} or a user will not know what to do: {message}"
            );
        }
    }

    #[test]
    fn a_supplied_password_gets_the_plain_error_not_the_rsign2_advice() {
        // The advice is only right when no password was given. Someone who
        // supplied the wrong one should be told that, not sent chasing rsign2.
        let pair = KeyPair::generate_encrypted_keypair(Some("correct".to_owned()))
            .expect("generate keypair");
        let Err(err) = SigningKey::from_str(&secret_key_text(&pair), Some("wrong".to_owned()))
        else {
            panic!("the wrong password must not unlock the key");
        };
        assert!(
            !err.to_string().contains("rsign2"),
            "misleading advice for a genuinely wrong password: {err}"
        );
    }

    #[test]
    fn a_missing_password_never_prompts() {
        // The minisign crate treats `None` as "ask on the terminal", which in CI
        // means dying with "Device not configured" or hanging forever. This must
        // fail cleanly instead.
        let pair = KeyPair::generate_encrypted_keypair(Some("secret".to_owned()))
            .expect("generate keypair");
        let Err(err) = SigningKey::from_str(&secret_key_text(&pair), None) else {
            panic!("an encrypted key must not load without its password");
        };
        assert!(matches!(err, Error::Key(_)), "unexpected error: {err}");
    }

    #[test]
    fn rejects_nonsense() {
        let Err(err) = SigningKey::from_str("clearly not a key", None) else {
            panic!("nonsense should not load as a key");
        };
        assert!(matches!(err, Error::Key(_)));
    }

    #[test]
    fn signatures_verify_with_the_crate_tauri_uses() {
        let dir = tempfile::tempdir().expect("temp dir");
        let artifact = dir.path().join("app.AppImage");
        let bytes = b"pretend installer bytes";
        std::fs::write(&artifact, bytes).expect("write artifact");

        let pair = keypair();
        let key = SigningKey::from_str(&secret_key_text(&pair), None).expect("load key");
        let signature = key.sign_file(&artifact).expect("sign");

        assert!(
            verify_like_tauri(&signature, bytes, &pair),
            "the signature this tool writes must verify the way Tauri verifies it"
        );
    }

    #[test]
    fn a_signature_does_not_verify_against_different_bytes() {
        let dir = tempfile::tempdir().expect("temp dir");
        let artifact = dir.path().join("app.AppImage");
        std::fs::write(&artifact, b"the real installer").expect("write artifact");

        let pair = keypair();
        let key = SigningKey::from_str(&secret_key_text(&pair), None).expect("load key");
        let signature = key.sign_file(&artifact).expect("sign");

        assert!(
            !verify_like_tauri(&signature, b"a tampered installer", &pair),
            "a signature must not validate bytes it does not cover"
        );
    }

    #[test]
    fn a_signature_does_not_verify_against_another_key() {
        let dir = tempfile::tempdir().expect("temp dir");
        let artifact = dir.path().join("app.AppImage");
        let bytes = b"the real installer";
        std::fs::write(&artifact, bytes).expect("write artifact");

        let pair = keypair();
        let key = SigningKey::from_str(&secret_key_text(&pair), None).expect("load key");
        let signature = key.sign_file(&artifact).expect("sign");

        assert!(
            !verify_like_tauri(&signature, bytes, &keypair()),
            "a signature must not validate under an unrelated key"
        );
    }

    #[test]
    fn public_keys_round_trip_through_the_tauri_encoding() {
        let pair = keypair();
        let raw = pair.pk.to_box().expect("box pk").into_string();
        let encoded = base64::engine::general_purpose::STANDARD.encode(&raw);
        decode_public_key(&encoded).expect("base64 public key should decode");
        decode_public_key(&raw).expect("raw public key should decode");
    }
}
